name: Bounty
api: [3.0.0-ALPHA9, 3.0.0-ALPHA12]
main: Infernus101\Main
version: 2.0.1
author: VMPE Development Team
description: Bounty plugin for Faction servers.
commands:
  bounty:
    description: "Bounty help"
